"use client";

import React, { useEffect, useMemo, useState } from "react";
import { Info, Minus, Plus } from "lucide-react";
import Modal from "@/components/modal/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type {
  AssetCategory,
  CreateAssetItemPayload,
} from "@/redux/slice/admin/asset-mgt/admin-asset";

type DraftRow = {
  id: string;
  name: string;
  tag: string;
};

type Props = {
  visible: boolean;
  onClose: () => void;
  onSubmit: (payloads: CreateAssetItemPayload[]) => Promise<void> | void;
  loading?: boolean;
  category: AssetCategory | null;
  estateId: string;
};

function createDraftRow(baseName: string, index: number): DraftRow {
  const cryptoObj = globalThis.crypto as { randomUUID?: () => string } | undefined;
  const id =
    cryptoObj?.randomUUID?.() ??
    `${Date.now()}-${Math.random().toString(16).slice(2)}-${index}`;
  return {
    id,
    name: baseName ? `${baseName} ${index + 1}` : "",
    tag: "",
  };
}

const todayIso = () => new Date().toISOString().slice(0, 10);

export default function AssetFormModal({
  visible,
  onClose,
  onSubmit,
  loading = false,
  category,
  estateId,
}: Readonly<Props>) {
  const [baseName, setBaseName] = useState("");
  const [quantity, setQuantity] = useState(1);
  const [rows, setRows] = useState<DraftRow[]>([createDraftRow("", 0)]);
  const [amount, setAmount] = useState("");
  const [useFullLife, setUseFullLife] = useState("");
  const [datePurchased, setDatePurchased] = useState<string>(todayIso());

  const categoryId = useMemo(
    () => category?.id || category?._id || "",
    [category],
  );

  useEffect(() => {
    if (!visible) return;
    setBaseName("");
    setQuantity(1);
    setRows([createDraftRow("", 0)]);
    setAmount("");
    setUseFullLife("");
    setDatePurchased(todayIso());
  }, [visible]);

  useEffect(() => {
    setRows((prev) => {
      const next: DraftRow[] = [];
      for (let i = 0; i < quantity; i += 1) {
        const existing = prev[i];
        if (existing) {
          const updatedName = baseName
            ? `${baseName} ${i + 1}`
            : existing.name && !existing.name.startsWith(baseName)
              ? existing.name
              : "";
          // Only auto-update name when it still matches the previous base pattern,
          // otherwise preserve user edits.
          const looksAutoGenerated =
            existing.name === "" || /\s\d+$/.test(existing.name);
          next.push({
            ...existing,
            name: looksAutoGenerated ? updatedName : existing.name,
          });
        } else {
          next.push(createDraftRow(baseName, i));
        }
      }
      return next;
    });
  }, [quantity, baseName]);

  const updateRow = (id: string, patch: Partial<DraftRow>) => {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  };

  const amountNum = Number(amount);
  const lifeNum = Number(useFullLife);
  const validCommon =
    !Number.isNaN(amountNum) &&
    amountNum > 0 &&
    !Number.isNaN(lifeNum) &&
    lifeNum > 0 &&
    Boolean(datePurchased);

  const canSubmit =
    Boolean(categoryId) &&
    Boolean(estateId) &&
    rows.length > 0 &&
    validCommon &&
    rows.every((r) => r.name.trim().length >= 2 && r.tag.trim().length >= 1);

  const handleSubmit = async () => {
    if (!canSubmit) return;
    const payloads: CreateAssetItemPayload[] = rows.map((r) => ({
      name: r.name.trim(),
      tag: r.tag.trim(),
      assetCategoryId: categoryId,
      estateId,
      amount: amountNum,
      useFullLife: lifeNum,
      datePurchased,
    }));
    await onSubmit(payloads);
  };

  return (
    <Modal visible={visible} onClose={onClose}>
      <div className="pr-8 space-y-5">
        <div className="flex flex-col items-start gap-2">
          <h2 className="text-xl font-semibold text-gray-900">Add Asset</h2>
          <span className="inline-flex items-start gap-1 text-xs text-blue-400">
            <Info className="w-3.5 h-3.5 text-blue-400" />
            All Assets must be added with unique codes
          </span>
        </div>

        <div className="space-y-2">
          <label
            htmlFor="add-asset-category"
            className="text-sm font-medium text-gray-700"
          >
            Asset Category
          </label>
          <Input
            id="add-asset-category"
            value={category?.name ?? ""}
            readOnly
            disabled
            className="h-11 bg-gray-50"
          />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="space-y-2">
            <label
              htmlFor="add-asset-amount"
              className="text-sm font-medium text-gray-700"
            >
              Amount (₦)
            </label>
            <Input
              id="add-asset-amount"
              inputMode="numeric"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="50000"
              className="h-11"
            />
          </div>

          <div className="space-y-2">
            <label
              htmlFor="add-asset-life"
              className="text-sm font-medium text-gray-700"
            >
              Useful life (yrs)
            </label>
            <Input
              id="add-asset-life"
              inputMode="numeric"
              value={useFullLife}
              onChange={(e) => setUseFullLife(e.target.value)}
              placeholder="5"
              className="h-11"
            />
          </div>

          <div className="space-y-2">
            <label
              htmlFor="add-asset-date"
              className="text-sm font-medium text-gray-700"
            >
              Date Purchased
            </label>
            <Input
              id="add-asset-date"
              type="date"
              value={datePurchased}
              onChange={(e) => setDatePurchased(e.target.value)}
              className="h-11"
            />
          </div>
        </div>

        <div className="space-y-2">
          <label
            htmlFor="add-asset-base-name"
            className="text-sm font-medium text-gray-700"
          >
            Asset Name
          </label>
          <div className="flex items-stretch gap-2">
            <Input
              id="add-asset-base-name"
              value={baseName}
              onChange={(e) => setBaseName(e.target.value)}
              placeholder="e.g. Generator"
              className="h-11 flex-1"
            />
            <div className="flex items-center gap-2 rounded-md border border-input px-2">
              <button
                type="button"
                aria-label="Decrease quantity"
                onClick={() => setQuantity((q) => Math.max(1, q - 1))}
                className="h-7 w-7 grid place-items-center rounded hover:bg-muted cursor-pointer"
              >
                <Minus className="w-3.5 h-3.5" />
              </button>
              <span className="min-w-6 text-center text-sm font-medium">
                {quantity}
              </span>
              <button
                type="button"
                aria-label="Increase quantity"
                onClick={() => setQuantity((q) => Math.min(50, q + 1))}
                className="h-7 w-7 grid place-items-center rounded hover:bg-muted cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>

        <div className="space-y-3">
          {rows.map((row, idx) => (
            <div
              key={row.id}
              className="grid grid-cols-1 md:grid-cols-3 items-center gap-2"
            >
              <Input
                value={row.name}
                onChange={(e) => updateRow(row.id, { name: e.target.value })}
                placeholder={`${baseName || "Asset"} ${idx + 1}`}
                className="h-11"
                aria-label={`Asset ${idx + 1} name`}
              />
              <div className="hidden sm:flex h-11 w-9 items-center justify-center rounded-md bg-[#D0DFF280] text-[#0150AC] text-sm font-semibold">
                #
              </div>
              <Input
                value={row.tag}
                onChange={(e) => updateRow(row.id, { tag: e.target.value })}
                placeholder="Asset code"
                className="h-11"
                aria-label={`Asset ${idx + 1} code`}
              />
            </div>
          ))}
        </div>

        <div className="flex flex-col-reverse sm:grid sm:grid-cols-2 gap-3 pt-2">
          <Button
            variant="outline"
            onClick={onClose}
            disabled={loading}
            className="h-11"
          >
            Cancel
          </Button>
          <Button
            className="h-11 text-white"
            style={{ backgroundColor: "#0150AC" }}
            disabled={!canSubmit || loading}
            onClick={handleSubmit}
          >
            {loading
              ? "Saving..."
              : `Add Asset${rows.length > 1 ? "s" : ""}`}
          </Button>
        </div>
      </div>
    </Modal>
  );
}
